language: rust
rust:
- stable
- beta
- nightly
cache: cargo
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
before_deploy:
- cargo doc
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target/docs/
  github_token: "$GH_REPO_TOKEN"
  on:
    branch: master
    rust: stable