[package]
name = "safe_matmul"
version = "0.1.0"
authors = ["Nixon <nixon.emoony@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2.6"
[dev-dependencies]
rand = "0.6.1"


[lib]
name = "matlib"
path = "src/lib.rs"

